name: lenoid
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: 4.6.5
  html: 0.15.3
  dio: 5.1.2
  google_fonts: 4.0.4
  logger: ^1.3.0
  responsive_grid: ^2.2.0
  extended_image: ^8.0.1
  responsive_grid_list: ^1.3.2
  flutter_staggered_grid_view: ^0.6.2
  cached_network_image: ^3.2.3
  flutter_cache_manager: 3.3.0
  easy_refresh: ^3.3.1+2
  dio_smart_retry: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
