name: Build and Deploy Debug Flutter App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install and set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        cache: true

    - name: Get dependencies
      run: flutter pub get

    - name: Cache build directory
      uses: actions/cache@v3
      with:
        path: build
        key: ${{ runner.os }}-build-${{ hashFiles('**/build') }}
        restore-keys: |
          ${{ runner.os }}-build-
 
    - name: Build Android debug app
      run: |
        mkdir -pv build/app/outputs/debug
        flutter config --enable-android --no-analytics
        flutter build apk --debug --no-tree-shake-icons
        mv build/app/outputs/flutter-apk/*-debug.apk build/app/outputs/debug

    - name: Build Linux debug app
      run: |
        sudo apt-get update -y
        sudo sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev

        flutter config --enable-linux-desktop
        flutter build linux --debug --no-tree-shake-icons

    - name: Upload Android artifacts
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: build/app/outputs/debug/app-debug.apk

    - name: Archive Linux artifacts
      uses: actions/upload-artifact@v3
      with:
        name: app-linux_64
        path: build/linux/x64/debug/bundle/